$(document).ready(function(){$('#checkout_chkbx_store_payment_details').click(function(){if($(this).is(':checked')){$('.checkout_stripe_complete').hide();$('.checkout_stripe_next').show();}
else{$('.checkout_stripe_next').hide();$('.checkout_stripe_complete').show();}});$(document.body).on('click','.checkout_btn_stripe',function(){$this=$(this);var $temp_button_html=$this.parent().html();var $saved_card=$this.attr('saved-card');$('.btn').addClass('disabled');if($('#checkout_chkbx_store_payment_details').length==0){$message=$this.parent().parent().parent().find('.message-danger');}
else{if($('#checkout_chkbx_store_payment_details').is(':checked')){$message=$this.parent().parent().parent().find('.message-danger.checkout_stripe_next');}
else{$message=$this.parent().parent().parent().find('.message-danger.checkout_stripe_complete');}}
$message.text('').hide();$this=$this.parent();$this.html(btn_processing_html);if($saved_card=='yes'){$.ajax({url:"/exec/ajax_checkout_stripe_payment.php",dataType:"json",data:{},type:"post",success:function(data){if(data.result){document.location=data.link;}
else{$this.html($temp_button_html);$message.text(data.message).slideToggle(300);$('.btn').removeClass('disabled');}}});}
else{Stripe.createToken({number:$('#card_number').val(),cvc:$('#card_security_code').val(),exp_month:$('#card_month').val(),exp_year:$('#card_year').val()},function(status,response){if(response.error){$this.html($temp_button_html);if(response.error.code=='invalid_expiry_month'){response.error.message='Your card’s expiration date doesn’t seem correct.';}
$message.text(response.error.message).slideToggle(300);$('.btn').removeClass('disabled');}else{var token=response['id'];var $script_url=$('#checkout_chkbx_store_payment_details').is(':checked')||$('#checkout_chkbx_store_payment_details').length==0?"/exec/ajax_checkout_stripe_save_card.php":"/exec/ajax_checkout_stripe_payment.php";$.ajax({url:$script_url,dataType:"json",data:{stripeToken:token,billing_same_as_shipping:$('#checkout_chkbx_billing_same_as_shipping').is(':checked')?1:0,store_card:$('#checkout_chkbx_store_payment_details').is(':checked')?1:0,card_type:$('#card_type').val(),card_number:$('#card_number').val(),card_security_code:$('#card_security_code').val(),card_month:$('#card_month').val(),card_year:$('#card_year').val(),billing_recipient_name:$('#billing_recipient_name').val(),billing_street_address1:$('#billing_street_address1').val(),billing_street_address2:$('#billing_street_address2').val(),billing_city:$('#billing_city').val(),billing_country:$('#billing_country option:selected').text(),billing_country_id:$('#billing_country').val(),billing_state:$('#billing_state').val(),billing_state_input:$('#billing_state_input').val(),billing_zip_code:$('#billing_zip_code').val(),billing_phone:$('#billing_phone').val()},type:"post",success:function(data){if(data.result){if($('#checkout_chkbx_store_payment_details').is(':checked')||$('#checkout_chkbx_store_payment_details').length==0){document.location.reload();}
else{document.location=data.link;}}
else{$this.html($temp_button_html);$message.text(data.message).slideToggle(300);$('.btn').removeClass('disabled');}}});}});}
return false;});});