jQuery(document).ready(function($){var $sent_invitations_today_count=0;$('.tracking .tab a').click(function(e){e.preventDefault()
$(this).tab('show')});function easeInOutExpo(currentIteration,startValue,changeInValue,totalIterations){if((currentIteration/=totalIterations/2)<1){return changeInValue/2*Math.pow(2,10*(currentIteration-1))+startValue;}
return changeInValue/2*(-Math.pow(2,-10*--currentIteration)+2)+startValue;}
$('.share-code .em').click(function(e){e.preventDefault()
$('.via-email .form-control').first().focus();$('html, body').animate({scrollTop:$("#via-email").offset().top-100},400,easeInOutExpo);});$('.via-email input.form-control').focus(function(e){e.preventDefault()
$(this).parent().next().addClass('show');});var inviteClip=new Clipboard('#invite-code',{text:function(trigger){return trigger.value;}});inviteClip.on('success',function(e){$('.input-wrap').addClass('copied');$('#invite-code').focus().select();setTimeout(function(){$('.input-wrap').removeClass('copied');},2500);console.log(e);});$('.page-rewards .progress-bar').addClass('shown');$('#email').focus();$('#email').blur(function(){$.ajax({url:"/exec/ajax_email_in_system.php",dataType:"json",data:{email:$("#email").val()},type:"post",success:function(data){if(data.result==0){$('.block-already-account').show();$('.block-sign-in').hide();}
else{$('.block-already-account').hide();$('.block-sign-in').show();$('#but_already_account').hide();}}});});$('#email2').blur(function(){$.ajax({url:"/exec/ajax_email_in_system.php",dataType:"json",data:{email:$("#email2").val()},type:"post",success:function(data){if(data.result==0){$('.block-already-account2').show();$('.block-sign-in2').hide();}
else{$('.block-already-account2').hide();$('.block-sign-in2').show();$('#but_already_account2').hide();}}});});$('#but_create_new_account').click(function(){$('.block-sign-in').slideUp();$('.block-create-account, .block-already-account').slideDown();$message=$('.message-danger');$message.text('').hide();$('#buttonCreateAccountConfirmOther').removeClass('disabled');return false;});$('#but_create_new_account2').click(function(){$('.block-sign-in2').slideUp();$('.block-create-account2, .block-already-account2').slideDown();$message=$('.message-danger');$message.text('').hide();$('#buttonCreateAccountConfirmOther2').removeClass('disabled');return false;});if(typeof $sent_invitations_today!=="undefined"){$.each($sent_invitations_today,function(index,value){$('.input-invite').each(function(){var $this=$(this);if($this.attr('disabled')!="disabled"){$this.val(value).attr('disabled',true).parent().addClass('disabled show');return false;}});});$sent_invitations_today_count=$sent_invitations_today.length;if($sent_invitations_today_count>=8){$('#buttonSendInvitations').text('8 Invites Sent Today').addClass('disabled');}}
$('#buttonSendInvitations').click(function(){if(have_first_name===false){$('#modal_save_user_name').show();$('#modal_first_name').focus();return false;}
else{$('#buttonSendInvitations').addClass('disabled').text('PROCESSING...');var $recipient_list=[];$('.input-invite').each(function(){var $this=$(this);var $id=$this.attr('id');if(isEmail($('#'+$id).val())&&$('#'+$id).attr('disabled')!="disabled"){$recipient_list.push($('#'+$id).val());$this.val('');}});var uniqueNames=[];$.each($recipient_list,function(i,el){if($.inArray(el,uniqueNames)===-1)uniqueNames.push(el);});$recipient_list=uniqueNames;$.each($recipient_list,function(index,value){$('.input-invite').each(function(){var $this=$(this);if($this.attr('disabled')!="disabled"){$this.val(value).attr('disabled',true).parent().addClass('disabled');return false;}});$sent_invitations_today_count++;$('.input-invite:not([disabled])').first().focus();});if($sent_invitations_today_count>=8){$('#warning_8_emails').show();}
var params={recipient_list:$recipient_list,message:''}
$.getJSON('../exec/ajax_ma_send_invitation.html',params,function(data){if(data.result==1){getEmailInvitations();$('#buttonSendInvitations').html('<div class="btn-mes-error display">'+$recipient_list.length+' Invites Sent</div></button>');setInterval('$("#buttonSendInvitations").html("Send Email Invites").blur(); $(".btn").removeClass("disabled");',4000);}
if(data.result==2){getEmailInvitations();$('#buttonSendInvitations').html('8 Invites Sent Today').blur();}});}});$('#buttonSaveName').click(function(){$('.modal-error').text('').hide();$.post("../exec/ajax_save_names.html",{first_name:$('#modal_first_name').val(),last_name:$('#modal_last_name').val()},function(data){if(data.result==0){$('.modal-error').text(data.content).show();}
else{have_first_name=true;$('#modal_save_user_name').hide();$('#buttonSendInvitations').click();}},"json");});});function getEmailInvitations(){$.ajax({url:"/exec/ajax_get_email_invitations.php",dataType:"json",data:{},type:"post",success:function(data){$('#block_sent_email_invitations').html(data.html);}});}